<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <title>Page Title</title>
    </head>
    <body>
        <div class='position-absolute top-50 start-50 translate-middle'>
            <button id='button' class='btn btn-primary btn-lg' onclick='mulai()'> Click Here! </button>
            <div id='iloveyou' style='display: none;'>
                <h2 class='text-center'>Aku sayang kamu<br>&#10084;&#65039;</h2>
            </div>
        </div>
        <span id='hati' class='fixed-bottom text-center my-3' onclick='hati()'></span>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.19/dist/sweetalert2.all.min.js"></script>
        <script type="text/javascript">
            const author = 'Adit';
            document.getElementById('hati').innerHTML = `Made with &#10084;&#65039; by ${author}`;
            const swals = Swal.mixin({
                cancelButtonColor: '#d33',
                confirmButtonColor: '#3085d6',
            });
            async function mulai(){
                await swals.fire('Halo Cantik', 'Aku ada pertanyaan nih buat kamu', 'question');
                await swals.fire('Jawab yang jujur ya!');
                await swals.fire('Awas aja kalo boong!!','','error');
                var { value: nama } = await swals.fire({
                    title: 'Masukin nama kamu dulu',
                    input: 'text',
                    showCancelButton: true,
                });
                if(nama){
                    var { isConfirmed: sayang } = await swals.fire({
                        title: `${nama} sayang ga sama ${author}`,
                        confirmButtonText: 'Sayang',
                        cancelButtonText: 'Gak',
                        showCancelButton: true,
                    });
                    if(sayang){
                        await swals.fire('Aku juga sayang banget sama kamu');
                        var { value: persen } = await swals.fire({
                            title: 'Seberapa sayang emangnya?',
                            icon: 'question',
                            input: 'range',
                            inputLabel: 'Antara 1-100 ya',
                            inputAttributes: {
                                min: 1,
                                max: 100,
                            },
                            inputValue: 50
                        });
                        if(persen){
                            await swals.fire(`Makasih ya udah sayang sama ${author} ${persen}%`);
                            var { isConfirmed: kangen } = await swals.fire({
                                title: 'Sekarang kamu kangen ga sama aku?',
                                confirmButtonText: 'Kangen',
                                cancelButtonText: 'Gak!',
                                showCancelButton: true,
                            });
                            if(kangen){
                                await swals.fire('Huhu iya aku juga kangen kamu :((');
                                await swals.fire('Terakhir deh sayang');
                                await swals.fire('Coba klik ikon hati di paling bawah dong');
                            } else {
                                //gak kangen
                            }
                        }
                    } else {
                        //gak sayang
                    }
                } else {
                    //gak isi nama
                }
            }
        function hati(){
            document.getElementById('button').style = 'display: none';
            document.getElementById('iloveyou').style = '';
        }
        </script>
        <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->
    </body>
</html>
